[build]
  command = "yarn build"
  publish = "public/"

[dev]
  command = "yarn start"
  publish = "public/"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  force = true
  from = "/effection/api/*"
  status = 200
  to = "https://v2--effection-api.netlify.app/:splat"

[[redirects]]
  from = "/*"
  to = "/effection/:splat"
