name: covector status
on: [pull_request]

jobs:
  covector-status:
    runs-on: ubuntu-latest
    outputs:
      statoos: ${{ steps.covector.outputs.status }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - run: yarn install --immutable
      - run: yarn prepack
      - name: covector status
        uses: jbolda/covector/packages/action@main
        id: covector
        with:
          command: "status"
          comment: true
