name: TNP Pull Requests

on:
  pull_request:
    branches:
    # - release-*
    - master

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn
      run: yarn
    - name: test
      run: yarn test
    - name: lint
      run: yarn lint
    - name: coverage
      run: |
        yarn coverage
        # yarn coveralls # error

  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@master
    - name: Beta Publish
      uses: actions/npm@master
      with:
        args: version "`node -e \"console.log(require('./package.json').version)\"`-`git log --pretty=format:'%h' -n 1 --skip 1`" --no-git-tag-version && npm publish --access=public
          # this can be refactored to multi-line steps as opposed to args without actions/npm@master but will require `echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc`. see './pr-merge.yml'.
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@master
    - name: Danger
      run: |
        cd .github
        yarn global add danger --dev
        export PATH="$(yarn global bin):$PATH"
        danger ci
      env: 
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB }}